name: Android Build

on:
  workflow_call:
    inputs:
      NODE_VERSION:
        default: "16.x"
        type: string
      JAVA_VERSION:
        description: "Java version for the build"
        default: "11"
        type: string
      MIMOTO_HOST:
        description: "Mimoto backend service URL"
        default: "https://api.sandbox.mosip.net"
        type: string
      ESIGNET_HOST:
        description: "Esignet backend service URL"
        default: "https://api.sandbox.mosip.net"
        type: string
      KEYSTORE_ALIAS:
        required: true
        default: androidbuildkey
        type: string
      KEYSTORE_PASSWORD:
        required: true
        default: password
        type: string
      UPLOAD_TO_ACTIONS:
        default: 'false'
        required: true
        type: string
      APPLICATION_THEME:
        description: "Application Theme"
        default: 'orange'
        type: string
      ALLOW_ENV_EDIT:
        description: "Edit ENV"
        default: 'true'
        type: string
      SERVICE_LOCATION:
        description: "Service Location"
        required: true
        default: "."
        type: string
      ANDROID_SERVICE_LOCATION:
        description: "Android Service Location"
        required: true
        default: "android"
        type: string
      BUILD_SCRIPT_LOCATION:
        description: "Android build script Location"
        required: true
        default: "scripts"
        type: string
      SCRIPT_NAME:
        description: "Build script name"
        required: true
        default: "./android-build.sh"
        type: string
      ANDROID_ARTIFACT_NAME:
        description: "Android Artifact name"
        default: "Android App"
        type: string
      ANDROID_ARTIFACT_PATH:
        description: "Android Artifact path"
        default: "android/app/build/outputs"
        type: string
      APPLICATION_TYPE:
        description: "Apk type"
        default: "release"
        type: string

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.NODE_VERSION }}

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: ${{ inputs.JAVA_VERSION }}

      - name: Cache npm dependencies
        uses: actions/cache@v3.3.1
        with:
          path: '~/.npm'
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install npm dependencies
        run: |
          cd ${{ inputs.SERVICE_LOCATION }}
          npm ci

      - name: Echo branch name
        run: |
          echo "BRANCH_NAME=$(echo ${{ github.ref }} | sed -e 's,.*/\(.*\),\1,')" >> $GITHUB_ENV

      - name: Generate Dummy keystore for build
        run: |
          keytool \
          -genkey -v \
          -storetype PKCS12 \
          -keyalg RSA \
          -keysize 2048 \
          -validity 10000 \
          -storepass $KEYSTORE_PASSWORD \
          -keypass $KEYSTORE_PASSWORD \
          -alias $KEYSTORE_ALIAS \
          -keystore android/app/${{ inputs.APPLICATION_TYPE }}.keystore \
          -dname "CN=io.mosip.residentapp,OU=,O=,L=,S=,C=US"
        env:
          KEYSTORE_PASSWORD: ${{ inputs.KEYSTORE_PASSWORD }}
          KEYSTORE_ALIAS: ${{ inputs.KEYSTORE_ALIAS }}

      - name: Create Build
        run: |
          cd ${{ inputs.SERVICE_LOCATION }}/${{ inputs.ANDROID_SERVICE_LOCATION }}
          cd ${{ inputs.BUILD_SCRIPT_LOCATION }}
          ${{ inputs.SCRIPT_NAME }} "${{ inputs.APPLICATION_TYPE }}"
        env:
          MIMOTO_HOST: ${{ inputs.MIMOTO_HOST }}
          ESIGNET_HOST: ${{ inputs.ESIGNET_HOST }}
          APPLICATION_THEME: ${{ inputs.APPLICATION_THEME }}
          RELEASE_KEYSTORE_ALIAS: ${{ inputs.KEYSTORE_ALIAS }}
          DEBUG_KEYSTORE_ALIAS: ${{ inputs.KEYSTORE_ALIAS }}
          RELEASE_KEYSTORE_PASSWORD: ${{ inputs.KEYSTORE_PASSWORD }}
          DEBUG_KEYSTORE_PASSWORD: ${{ inputs.KEYSTORE_PASSWORD }}
          CREDENTIAL_REGISTRY_EDIT: ${{ inputs.ALLOW_ENV_EDIT }}
      
      - name: Upload Artifact to Actions
        if: ${{ inputs.UPLOAD_TO_ACTIONS == 'true'}}
        uses: actions/upload-artifact@v3.1.1
        with:
          name: ${{ inputs.ANDROID_ARTIFACT_NAME }}
          path: ${{ inputs.ANDROID_ARTIFACT_PATH }}
          retention-days: 10
