name: Android Internal Build

on:
  workflow_call:
    inputs:
      MIMOTO_HOST:
        description: 'Mimoto backend service URL'
        required: true
        default: 'https://api.sandbox.mosip.net'
        type: string
      ESIGNET_HOST:
        description: 'Esignet backend service URL'
        required: true
        default: 'https://api.sandbox.mosip.net'
        type: string
      APPLICATION_THEME:
        description: 'Application Theme'
        required: true
        default: 'orange'
        type: choice
        options:
          - orange
          - purple
      PLAY_CONSOLE_RELEASE_DESCRIPTION:
        description: 'What to test'
        required: true
        default: 'QA-Triple environment'
        type: string
      CREDENTIAL_REGISTRY_EDIT:
        description: 'Edit Registry'
        required: true
        default: 'true'
        type: choice
        options:
          - false
          - true
    secrets:
      FIREBASE_SECRET:
        required: true
      ANDROID_KEYSTORE_FILE:
        required: true
      RELEASE_KEYSTORE_PASSWORD:
        required: true
      INJI_ANDROID_PLAY_STORE_CONFIG_JSON:
        required: true
      SLACK_URL:
        required: true

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Cache local npm repository
        uses: actions/cache@v3.0.11
        with:
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          path: ~/.npm

      - name: Cache local gradle repository
        uses: actions/cache@v3.0.11
        with:
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper

      - name: Install npm dependencies
        run: |
          npm ci

      - name: Create .env.local file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env.local > android/local.properties

      - name: Setup branch and env
        run: |
          # Strip git ref prefix from version
          echo "BRANCH_NAME=$(echo ${{ github.ref }} | sed -e 's,.*/\(.*\),\1,')" >> $GITHUB_ENV
          echo "GPG_TTY=$(tty)" >> $GITHUB_ENV

      - name: Setup branch and GPG public key
        run: |
          # Strip git ref prefix from version
          echo ${{ env.BRANCH_NAME }}
          echo ${{ env.GPG_TTY }}

          sudo apt-get --yes install gnupg2
          gpg2 --import ./.github/keys/mosipgpgkey_pub.gpg 
          gpg2 --quiet --batch --passphrase=${{secrets.gpg_secret}}  --allow-secret-key-import --import ./.github/keys/mosipgpgkey_sec.gpg

      - name: Setup Firebase
        run: |
          cd android
          if [ ! -z "$FIREBASE_SECRET" ] && [ -f app/google-services.json.gpg ];then rm -f app/google-services.json;gpg2 --quiet --batch --passphrase=$FIREBASE_SECRET --pinentry-mode loopback --decrypt --output app/google-services.json app/mosip-google-services.json.gpg;fi
        env:
          FIREBASE_SECRET: ${{ secrets.FIREBASE_SECRET }}

      - name: Generate keystore
        run: |
          echo "$ANDROID_KEYSTORE_FILE" > release.keystore.b64
          base64 -d -i release.keystore.b64 > android/app/release.keystore
        env:
          ANDROID_KEYSTORE_FILE: ${{ secrets.ANDROID_KEYSTORE_FILE }}

      - name: Create Google Play Config file
        run: |
          cd android
          echo "$INJI_ANDROID_PLAY_STORE_CONFIG_JSON" > play_config.json.b64
          base64 -d -i play_config.json.b64 > play_config.json
        env:
          INJI_ANDROID_PLAY_STORE_CONFIG_JSON: ${{ secrets.INJI_ANDROID_PLAY_STORE_CONFIG_JSON }}

      - name: Run Build
        run: |
          cd android/scripts
          ./internal-build.sh
        env:
          MIMOTO_HOST: ${{ inputs.MIMOTO_HOST }}
          ESIGNET_HOST: ${{ inputs.ESIGNET_HOST }}
          APPLICATION_THEME: ${{ inputs.APPLICATION_THEME }}
          RELEASE_KEYSTORE_ALIAS: androidreleasekey
          RELEASE_KEYSTORE_PASSWORD: '${{secrets.RELEASE_KEYSTORE_PASSWORD}}'
          SLACK_URL: '${{ secrets.SLACK_URL }}'
          PLAY_CONSOLE_RELEASE_DESCRIPTION: ${{ inputs.PLAY_CONSOLE_RELEASE_DESCRIPTION }}
          CREDENTIAL_REGISTRY_EDIT: ${{ inputs.CREDENTIAL_REGISTRY_EDIT }}

  upload-to-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Cache local npm repository
        uses: actions/cache@v3.0.11
        with:
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          path: ~/.npm

      - name: Cache local gradle repository
        uses: actions/cache@v3.0.11
        with:
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper

      - name: Install npm dependencies
        run: |
          npm i

      - name: Create .env.local file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env.local > android/local.properties

      - name: Setup branch and env
        run: |
          # Strip git ref prefix from version
          echo "BRANCH_NAME=$(echo ${{ github.ref }} | sed -e 's,.*/\(.*\),\1,')" >> $GITHUB_ENV
          echo "GPG_TTY=$(tty)" >> $GITHUB_ENV

      - name: Setup branch and GPG public key
        run: |
          # Strip git ref prefix from version
          echo ${{ env.BRANCH_NAME }}
          echo ${{ env.GPG_TTY }}

          sudo apt-get --yes install gnupg2
          gpg2 --import ./.github/keys/mosipgpgkey_pub.gpg 
          gpg2 --quiet --batch --passphrase=${{secrets.gpg_secret}}  --allow-secret-key-import --import ./.github/keys/mosipgpgkey_sec.gpg

      - name: Setup Firebase
        run: |
          cd android
          if [ ! -z "$FIREBASE_SECRET" ] && [ -f app/google-services.json.gpg ];then rm -f app/google-services.json;gpg2 --quiet --batch --passphrase=$FIREBASE_SECRET --pinentry-mode loopback --decrypt --output app/google-services.json app/mosip-google-services.json.gpg;fi
        env:
          FIREBASE_SECRET: ${{ secrets.FIREBASE_SECRET }}

      - name: Generate keystore
        run: |
          echo "$ANDROID_KEYSTORE_FILE" > release.keystore.b64
          base64 -d -i release.keystore.b64 > android/app/release.keystore
        env:
          ANDROID_KEYSTORE_FILE: ${{ secrets.ANDROID_KEYSTORE_FILE }}

      - name: Create Google Play Config file
        run: |
          cd android
          echo "$INJI_ANDROID_PLAY_STORE_CONFIG_JSON" > play_config.json.b64
          base64 -d -i play_config.json.b64 > play_config.json
        env:
          INJI_ANDROID_PLAY_STORE_CONFIG_JSON: ${{ secrets.INJI_ANDROID_PLAY_STORE_CONFIG_JSON }}

      - name: Run Build for upload
        run: |
          npx jetify
          cd android
          ./gradlew :app:assembleMosipRelease
        env:
          MIMOTO_HOST: ${{ inputs.MIMOTO_HOST }}
          ESIGNET_HOST: ${{ inputs.ESIGNET_HOST }}
          APPLICATION_THEME: ${{ inputs.APPLICATION_THEME }}
          RELEASE_KEYSTORE_ALIAS: androidreleasekey
          RELEASE_KEYSTORE_PASSWORD: '${{secrets.RELEASE_KEYSTORE_PASSWORD}}'
          CREDENTIAL_REGISTRY_EDIT: ${{ inputs.CREDENTIAL_REGISTRY_EDIT }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: ${{ github.event.inputs.buildname }}
          path: android/app/build/outputs/apk/mosip/release/
          retention-days: 5
