name:  Manual workflow to transfer docker images

on:
  workflow_call:
    inputs:
      DESTINATION_ORGANIZATION:
        description: 'Provide Docker Hub destination org'
        required: true
        default: ''
        type: string
    secrets:
      USERNAME:
        description: 'Provide Docker Hub username'
        required: true
      TOKEN:
        description: 'Provide Docker Hub token'
        required: true
      SLACK_WEBHOOK_URL:
        required: true

jobs:
  Image-transfer:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: update config.yml
        run: |
          cd release/vidivi
          echo "PWD: $( pwd )"
          echo "LS : $( ls ) "
          sed -i "s/username:.*/username: ${{ secrets.USERNAME }}/g" config.yml
          sed -i "s/token:.*/token: ${{ secrets.TOKEN }}/g" config.yml
          sed -i "s/destination_organization.*/destination_organization: ${{ github.event.inputs.DESTINATION_ORGANIZATION }}/g" config.yml
      - name: push images
        run: |
          cd release/vidivi
          sudo pip install python-pip
          sudo pip install docker
          sudo python3 vidivi.py push

      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,author,commit,workflow,job # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: failure() # Pick up events even if the job fails or is canceled.