name: Inji iOS Automation Build

on:
  workflow_dispatch:
    inputs:
      MIMOTO_HOST:
        description: 'Mimoto backend service URL'
        required: true
        default: 'https://api.sandbox.mosip.net'
        type: string
      ESIGNET_HOST:
        description: 'Esignet backend service URL'
        required: true
        default: 'https://api.sandbox.mosip.net'
        type: string
      APPLICATION_THEME:
        description: 'Application Theme'
        required: true
        default: 'orange'
        type: choice
        options:
          - orange
          - purple
      CREDENTIAL_REGISTRY_EDIT:
        description: 'Edit Registry'
        required: true
        default: 'true'
        type: choice
        options:
          - false
          - true

jobs:
  build_ios:
    name: Uploading app to Actions
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install npm dependencies
        run: |
          npm install

      - name: Install Pod
        run: |
          cd ios
          pod install
          pod install

      - name: Build iOS for automation on simulator
        run: |
          cd ios
          fastlane build_app_for_automation_on_simulator

      - name: Upload Inji.app artifact 
        uses: actions/upload-artifact@v3.1.1
        with:
          name: Inji
          path: ios/fastlane/Inji_app_file/Products/Applications/
          retention-days: 5

      - name: Upload Runner Log on Failure
        if: failure() # Only run this step if the previous steps failed
        uses: actions/upload-artifact@v3.1.1
        with:
          name: runner-log
          path: /Users/runner/Library/Logs/gym/
          retention-days: 1