name: Maven Sonar Analysis

on:
  workflow_call:
    inputs:
      SERVICE_LOCATION:
        required: true
        type: string
      SONAR_URL:
        required: false
        type: string
        default: 'https://sonarcloud.io'
      PROJECT_KEY:
        required: false
        type: string
        default: "mosip_${{ github.event.repository.name }}"
    secrets:
      SONAR_TOKEN:
        required: true
      SLACK_WEBHOOK_URL:
        required: true

jobs:
  maven-sonar-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Setup branch and env
        run: |
          # Strip git ref prefix from version
          echo "BRANCH_NAME=$(echo ${{ github.ref }} | sed -e 's,.*/\(.*\),\1,')" >> $GITHUB_ENV
          echo "GPG_TTY=$(tty)" >> $GITHUB_ENV
          echo "SONAR URL : ${{ inputs.SONAR_URL }}"


      - name: Analyze with SonarCloud
        run: |
          SERVICE_KEY=$(echo "${{ inputs.SERVICE_LOCATION }}" | tr '/' '-') 
          FULL_PROJECT_KEY="${{ inputs.PROJECT_KEY }}-${SERVICE_KEY}"
          cd ${{ inputs.SERVICE_LOCATION }} && \
          mvn -U -B verify sonar:sonar \
            -Dmaven.wagon.http.retryHandler.count=2 \
            -Dsonar.projectKey=${FULL_PROJECT_KEY} \
            -Dsonar.organization=${{ secrets.ORG_KEY }} \
            -Dsonar.host.url=${{ inputs.SONAR_URL }} \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.projectName=${{ github.event.repository.name }} \
            --file pom.xml -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,author,commit,workflow,job # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: "${{ github.event_name != 'pull_request' && failure() }}" # Pick up events even if the job fails or is canceled.
